version: '3.7'
services:
  mysql_container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: sanic
    ports:
      - "3306:3306"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"